### ISSUE TITLE
Disabling modem control signals to keep the session open

### ISSUE THREAD

**Issue by dawidi** [hackerb9/Tandy-Terminfo#5]
I hope you don't get mad at me, I keep expanding the scope of your project without ever even touching the actual terminfo :-)

I found another setting that makes an important difference: `stty clocal` - disable modem control signals.

* Without this setting (i.e. `-clocal`), whenever you exit terminal mode in TELCOM, it will "hang up" the session, kill any running process and log you out on the host.
* With this setting (i.e. `clocal`), the session on the host will stay open across TELCOM sessions, so you can e.g. start an upload script (like my `stor` mentioned in my first issue), exit TELCOM, enter BASIC, load a tokenized program (.BA, which cannot be uploaded through TELCOM because it isn't a plain-text .DO file), do a `SAVE "COM:98N1E",A` to send the de-tokenized version to the host, then return to TELCOM and hit ^D to finish the upload. Still a bit of a hassle, but maybe better than having to save a de-tokenized copy to a local .DO file before uploading it.
* This mode is also necessary if you plan on mixing I/O from a custom BASIC program into a TELCOM session on the host.

I had this working already, several months ago, but it broke and I couldn't figure out why - today I finally found out that `reset`ting the terminal (as in your .bash_profile example, but I had a different order of operations) resets some of the TTY settings to whatever **reset** considers "sane" values - among other things, it **disables clocal** which broke the above "save to COM from BASIC" workflow. So, it's important to do `reset` first and set up the details of the TTY afterwards.

**Comment by hackerb9** [comment]
Mad? Your bug reports have helped improve this project. even as it has grown beyond a simple TERMINFO entry. ☺ 

I've updated the td200 script to include clocal and changed the README to explain why. 

Your suggestions are always appreciated, so don't hesitate to file more bug reports.
